import = [
  "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.italic]
family = "BlexMono Nerd Font"
style = "Regular"

[window]
dynamic_title = true
option_as_alt = "OnlyLeft"
decorations = "Buttonless"
decorations_theme_variant = "Dark"

[window.padding]
x = 0
y = 0

