vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.loaded_netrw = 1 -- Disable netrw (file explorer)
vim.g.loaded_netrwPlugin = 1

vim.opt.clipboard = 'unnamedplus' -- Sync with system clipboard
vim.opt.completeopt = { 'menu', 'menuone', 'noselect' } -- Configure completion menu behavior
vim.opt.conceallevel = 2 -- Hide * markup for bold and italic, but not for substitutions
vim.opt.confirm = true -- Confirm to save changes before exiting a modified buffer
vim.opt.cursorline = true -- Highlight the current line
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.fillchars = { -- Customize characters for folds, separators, and more
  foldopen = '',
  foldclose = '',
  fold = ' ',
  foldsep = ' ',
  diff = '╱',
  eob = ' ',
}
vim.opt.foldlevel = 99 -- Set a high fold level to keep all folds open by default
vim.opt.ignorecase = true -- Ignore case in searches
vim.opt.inccommand = 'nosplit' -- Preview incremental substitutions without splitting
vim.opt.jumpoptions = 'view' -- Preserve view context when jumping
vim.opt.laststatus = 3 -- Use a global statusline
vim.opt.linebreak = true -- Wrap lines at convenient points
vim.opt.list = true -- Show invisible characters (tabs, spaces, etc.)
vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' } -- Customize list characters
vim.opt.mouse = 'a' -- Enable mouse support
vim.opt.number = true -- Show line numbers
vim.opt.pumblend = 10 -- Set popup menu transparency
vim.opt.pumheight = 10 -- Maximum number of entries in the popup menu
vim.opt.relativenumber = true -- Show relative line numbers
vim.opt.ruler = false -- Disable the default ruler
vim.opt.scrolloff = 4 -- Keep 4 lines of context above/below during scrolling
vim.opt.shiftround = true -- Round indentation to the nearest shiftwidth
vim.opt.shiftwidth = 2 -- Number of spaces for an indentation level
vim.opt.showmode = false -- Disable showing mode (handled by statusline)
vim.opt.sidescrolloff = 8 -- Keep 8 columns of context to the left/right during horizontal scrolling
vim.opt.signcolumn = 'yes' -- Always show the sign column to avoid text shifting
vim.opt.smartcase = true -- Ignore case unless the search contains uppercase letters
vim.opt.smartindent = true -- Automatically insert appropriate indents
vim.opt.spelllang = { 'en' } -- Set the spellcheck language to English
vim.opt.splitbelow = true -- Open new windows below the current one
vim.opt.splitkeep = 'screen' -- Keep the screen stable when splitting
vim.opt.splitright = true -- Open new windows to the right of the current one
vim.opt.swapfile = false -- Disable swap files
vim.opt.tabstop = 2 -- Number of spaces a tab counts for
vim.opt.termguicolors = true -- Enable true color support
vim.opt.timeoutlen = 300 -- Timeout for key sequences
vim.opt.undofile = true -- Enable persistent undo
vim.opt.undolevels = 10000 -- Maximum number of undo levels
vim.opt.updatetime = 200 -- Faster update time for CursorHold and swap files
vim.opt.virtualedit = 'block' -- Allow cursor movement beyond text in block visual mode
vim.opt.wildmode = 'longest:full,full' -- Command-line completion mode
vim.opt.winminwidth = 5 -- Minimum window width
-- vim.opt.wrap = false -- Disable line wrapping
